encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("newentry", views.newentry, name = "newentry"),
    path("editentry/<str:entry>", views.editentry, name = "editentry"),
    path("<str:entry>", views.GetEntry, name = "getentry")
 ]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.shortcuts import render
from markdown2 import markdown, markdown_path
from django.core.files import File

from . import util

class NewEntryForm(forms.Form):
    title =  forms.CharField(label="Entry Title")
    mdText = forms.CharField(widget=forms.Textarea(attrs={'id':'mdText', 'name':'mdText'})) 

class EditEntryForm(forms.Form):
    entry =  forms.CharField(label="Entry Title")
    content = forms.CharField(widget=forms.Textarea(attrs={'id':'editText', 'name':'editText', 'value':'content'})) 

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
    
def GetEntry(request, entry):
    text = util.get_entry(entry)
    if text is None:
        html = markdown_path("encyclopedia/templates/encyclopedia/Not Found.md")
        return render(request, "encyclopedia/notFound.html", {"html": html, "entry": entry})
    else:
        html = markdown(text)
        return render(request, "encyclopedia/entry.html", {"html": html, "entry": entry})
        
def newentry(request):
    if request.method=="POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data["mdText"]
            title = form.cleaned_data["title"]
            util.save_entry(title, content)
        else:
            return render(request, "encyclopedia/NewEntry.html", {
                "form":form
            })
            
    return render(request, "encyclopedia/NewEntry.html", {
        "form": NewEntryForm()
    })

def dispentry(request, entry):
    text = util.get_entry(entry)
    return render(request, "encyclopedia/editEntry2.html", {"entry": entry})
    if request.method =="POST":
        if form.is_valid():
            content = form.cleaned_data["editText"]
            title = form.cleaned_data["entry"]
            util.save_entry(title, content)
        else:
            return HttpResponse ("Invalid data")  
    data = {"title":"{{entry}}", "content":"mycontent"}        

def editentry(request, entry):
    content = util.get_entry(entry)
    data = {'entry':entry, 'content':content}
    form = EditEntryForm(data, initial=data)
    
    return render(request, "encyclopedia/editEntry.html", {
        "form":form, "entry":entry
    })

    

encyclopedia/templates/encyclopedia/CSSentry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia Entry
{% endblock %}

{% block body %}
	<p>
	<h1> My H1 before {entry} </h1>
    <h1> {{ entry }} </h1>

    <h4> 
        This will by my CSS entry
    </h4>
	
{% endblock %}

encyclopedia/templates/encyclopedia/NewEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
	<form action = "{% url 'encyclopedia:newentry' %}" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit">
	</form>
	
{% endblock %} 

encyclopedia/templates/encyclopedia/editEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry {{entry|safe}}
{% endblock %}

{% block body %}
	<form action = "{% url 'encyclopedia:editentry' entry=entry %}" method="post">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Submit"> 
	</form>
	
{% endblock %} 

encyclopedia/templates/encyclopedia/editEntry2.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry {{entry|safe}}
{% endblock %}

{% block body %}
	
	{{entry|safe}}
	
{% endblock %} 

encyclopedia/templates/encyclopedia/entry.html
{% block title %}
    {{entry|safe}}
{% endblock %}

{% block body %}
	{{html|safe}}
	<p>
	<a href="{% url 'encyclopedia:editentry' entry=entry %}"> Edit This Entry: {{entry|safe}} </a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:getentry' entry=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newentry' %}">Create New Page</a>
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/notFound.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{entry|safe}} Not Found
{% endblock %}

{% block body %}
	<h1> {{entry|safe}} Not Found </h1>
	{{html|safe}}
{% endblock %}